{% set name = "pytorch_toolbelt" %}
{% set version = "0.8.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytorch_toolbelt-{{ version }}.tar.gz
  sha256: a7a5126fbaeea68d7f7423cef540051554159f6f57b3af07dba8ee5b166cc9b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch >=1.11.0
    - torchvision
    - scipy >=1.4.0
    - opencv >=4.1

test:
  imports:
    - pytorch_toolbelt
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/BloodAxe/pytorch-toolbelt
  summary: PyTorch extensions for fast R&D prototyping and Kaggle farming
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
